# Generated by Django 5.0.2 on 2025-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('maintenance', 'صيانة'), ('new_installation', 'تركيب جديد'), ('system_upgrade', 'تطوير منظومة'), ('reinstallation', 'إعادة تركيب')], max_length=50)),
                ('engineer', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
