# Generated by Django 5.0.2 on 2025-02-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='engineer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='service_type',
            field=models.CharField(blank=True, choices=[('maintenance', 'صيانة'), ('new_installation', 'تركيب جديد'), ('system_upgrade', 'تطوير منظومة'), ('reinstallation', 'إعادة تركيب')], max_length=50, null=True),
        ),
    ]
